Update UnicornPythonAcquisitionExampleNumpy.py
Correcting line 118:

Old code: 
Uncorn.DeviceException
Exception: NameError: name 'Unicorn' is not defined. Did you mean: 'UnicornPy'?

New code:
UncornPy.DeviceException 
since the library is imported as UnicornPy, UnicornPy should be used instead of Unicorn